apps = [
    {"id": "0", "name": "OPĆE"},
    {"id": "56", "name": "PNN"},
    {"id": "4", "name": "PLAĆE"},
    {"id": "6", "name": "OBUKA"},
    {"id": "7", "name": "SERVIS"},
    {"id": "10", "name": "KADROVSKA"},
    {"id": "8", "name": "OSA"},
    {"id": "9", "name": "PRORACUN"},
    {"id": "11", "name": "KAMATE-K"},
    {"id": "12", "name": "LIKVIDATURA"},
    {"id": "13", "name": "GROBNI OČEVIDNIK"},
    {"id": "14", "name": "DOBAVLJAČI"},
    {"id": "15", "name": "GROBLJA"},
    {"id": "16", "name": "FINANCIJSKO"},
    {"id": "17", "name": "ROBNO"},
    {"id": "19", "name": "UGOVORI"},
    {"id": "20", "name": "DJELOVODNIK"},
    {"id": "21", "name": "POREZI"},
    {"id": "25", "name": "OSTALO"},
    {"id": "26", "name": "VRTIĆ"},
    {"id": "27", "name": "BLAGAJNA"},
    {"id": "28", "name": "KAMATE-V"},
    {"id": "29", "name": "SOCIJALA"},
    {"id": "31", "name": "PUTNI NALOZI"},
    {"id": "36", "name": "MATERIJALNO"},
    {"id": "37", "name": "REVIZIJA"},
    {"id": "39", "name": "ŠKOLOVANJE"},
    {"id": "30", "name": "JANA"},
    {"id": "34", "name": "RIZNICA"},
    {"id": "35", "name": "TRAJNI NALOZI"},
    {"id": "41", "name": "PDV"},
    {"id": "42", "name": "POČETNO STANJE"},
    {"id": "43", "name": "UPITI"},
    {"id": "44", "name": "ERV"},
    {"id": "45", "name": "DOPUSNICE"},
    {"id": "46", "name": "NAL. PROR. KORISNIKA"},
    {"id": "48", "name": "E - RAČUNI"},
    {"id": "50", "name": "KOLANJE"},
    {"id": "51", "name": "NEKRETNINE"},
    {"id": "1", "name": "KIS"},
    {"id": "3", "name": "PISARNICA"},
    {"id": "53", "name": "ŠKOLE - TOPLI OBROCI"},
    {"id": "54", "name": "PROMET"},
    {"id": "60", "name": "REGISTAR OSOBA"},
    {"id": "62", "name": "OPZ"},
    {"id": "55", "name": "DSN - EVIDENCIJA I OBRAČUN"},
    {"id": "52", "name": "POMORCI"},
    {"id": "64", "name": "IPPORTAL"},
    {"id": "61", "name": "REDOK"},
    {"id": "63", "name": "JOPPD NEOPOREZIVO"},
    {"id": "67", "name": "MINI RIZNICA"},
    {"id": "65", "name": "POSLOVNO SAVJETOVANJE"},
    {"id": "66", "name": "TRANSPARENTNOST"},
    {"id": "68", "name": "ELEKTRONIČKI SERVISI"},
]